# Generated by Django 2.2 on 2021-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('view_count', models.IntegerField()),
                ('subscriber_count', models.IntegerField()),
                ('video_count', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
