# Generated by Django 2.2 on 2021-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='previous_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
