# Generated by Django 2.2 on 2021-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210603_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='increased_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
