# Generated by Django 2.2 on 2021-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_youtubevideo_increased_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='view_median',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
